[package]
name = "phantombyte"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.3.1"
postgrest = "1.6.0"
shuttle-actix-web = "0.30.1"
shuttle-runtime = "0.30.0"
tokio = "1.26.0"
tracing = "0.1.40"
